/*
COMENTARIOS MULTILINEA
*/

-- De una sola linea				NO IMPORTAN LAS MAYUSCULAS
-- DROP DATABASE basedatos;			BORRA BASES DE DATOS
-- DROP TABLE python;				BORRA TABLAS

-- CREATE DATABASE glosario;

CREATE TABLE DATOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255)NOT NULL,
    apellido VARCHAR(255)NOT NULL,
    password VARCHAR(255)NOT NULL,
    año TIME
); 

CREATE TABLE palabrasReservadas(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	palabra VARCHAR(255)NOT NULL,
    lenguaje VARCHAR(255)NOT NULL,
	significado VARCHAR(255)NOT NULL,
	ejemplo VARCHAR(255)NOT NULL
);

